models/node.py
from . import ModelMixin
from . import db
from . import timestamp


class Node(db.Model, ModelMixin):
    __tablename__ = 'nodes'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String())
    description = db.Column(db.String())
    # has relationship with topic
    topics = db.relationship('Topic', backref="node")

    def __init__(self, form):
        self.name = form.get('name', '')
        self.description = form.get('description', '')

models/topic.py
from . import ModelMixin
from . import db
from . import timestamp
import time


class Topic(db.Model, ModelMixin):
    __tablename__ = 'topics'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    content = db.Column(db.String(1000))
    created_time = db.Column(db.String(), default=0)
    comments_num = db.Column(db.Integer)
    read_num = db.Column(db.Integer)
    # has relationship with comments
    comments = db.relationship('Comment', backref="topic")
    #
    node_id = db.Column(db.Integer, db.ForeignKey('nodes.id'))
    auth_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, form):
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        # created_time
        format = '%Y/%m/%d %H:%M:%S'
        v = timestamp() + 3600 * 8
        valuegmt = time.gmtime(v)
        dt = time.strftime(format, valuegmt)
        self.created_time = dt
        self.comments_num = 0
        self.read_num = 0

    def valid(self):
        if len(self.title) > 0:
            return True
        else:
            return False

routes/comment.py
from models.comment import Comment
from routes import *


main = Blueprint('comment', __name__)

Model = Comment


@main.route('/add', methods=['POST'])
@login_required
def add():
    form = request.form
    u = current_user()
    m = Model(form)
    m.topic_id = int(form.get('topic_id'))
    m.auth_id = u.id
    if m.valid():
        m.save()
    else:
        print('评论不能为空')
    # change topic.comments_num
    m.topic.comments_num += 1
    m.topic.save()
    return redirect(url_for('topic.show', id=m.topic_id))

routes/node.py
from models.node import Node
from models.topic import Topic
from routes import *


main = Blueprint('node', __name__)

Model = Node


@main.route('/')
def index():
    ms = Model.query.all()
    return render_template('node_index.html', node_list=ms)


@main.route('/new')
def new():
    return render_template('node_new.html')


@main.route('/<int:id>')
def show(id):
    print('show node, ', id, type(id))
    m = Model.query.get(id)
    print(id, m)
    return render_template('node.html', node=m)


@main.route('/edit/<id>')
def edit(id):
    t = Model.query.get(id)
    return render_template('node_edit.html', todo=t)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    m = Model(form)
    m.save()
    return redirect(url_for('.index'))


@main.route('/update/<int:id>', methods=['POST'])
def update(id):
    form = request.form
    t = Model.query.get(id)
    t.update(form)
    return redirect(url_for('.index'))


@main.route('/delete/<int:id>')
@admin_required
def delete(id):
    t = Model.query.get(id)
    t.delete()
    return redirect(url_for('.index'))

routes/topic.py
from models.topic import Topic
from routes import *


main = Blueprint('topic', __name__)

Model = Topic


@main.route('/')
def index():
    ms = Model.query.all()
    # ms = Model.query.order_by(Model.id.desc()).all()
    return render_template('topic_index.html', topic_list=ms)


@main.route('/new')
@login_required
def new():
    return render_template('topic_new.html')


@main.route('/<int:id>')
def show(id):
    m = Model.query.get(id)
    m.read_num += 1
    m.save()
    return render_template('topic.html', topic=m)


@main.route('/edit/<id>')
def edit(id):
    t = Model.query.get(id)
    return render_template('topic_edit.html', todo=t)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    u = current_user()
    m = Model(form)
    m.node_id = int(form.get('node_id'))
    m.auth_id = u.id
    if m.valid():
        m.save()
    else:
        print('主题不能为空')
    return redirect(url_for('node.show', id=m.node_id))


@main.route('/update/<int:id>', methods=['POST'])
def update(id):
    form = request.form
    t = Model.query.get(id)
    t.update(form)
    return redirect(url_for('.index'))


@main.route('/delete/<int:id>')
def delete(id):
    t = Model.query.get(id)
    t.delete()
    return redirect(url_for('.index'))

routes/user.py
from models.user import User
# from models.topic import Topic
from routes import *


main = Blueprint('user', __name__)

Model = User


@main.route('/')
def login_view():
    # ms = Model.query.all()
    return render_template('user_login.html')


@main.route('/login', methods=['POST'])
def login():
    form = request.form
    u = User(form)
    user = Model.query.filter_by(username=u.username).first()
    if u.valid_login(user):
        session.permanent = True
        session['uid'] = user.id
        return redirect(url_for('index.index'))
    else:
        return redirect(url_for('.login_view'))


@main.route('/register', methods=['POST'])
def register():
    form = request.form
    u = User(form)
    if u.valid():
        u.save()
        session.permanent = True
        session['uid'] = u.id
        return redirect(url_for('index.index'))
    else:
        return redirect(url_for('.login_view'))


@main.route('/logout')
def logout():
    p = session.pop('uid')
    print('logout: pop uid', p)
    return redirect(url_for('index.index'))


@main.route('/update_username', methods=['POST'])
def update_username():
    u = current_user()
    username = request.form.get('username', '')
    print('username', username)
    if u.change_username(username):
        print('修改成功')
    else:
        print('用户名修改失败')
    return redirect(url_for('user.profile'))


@main.route('/update_password', methods=['POST'])
def update_password():
    u = current_user()
    password = request.form.get('password', '')
    print('password', password)
    if u.change_password(password):
        print('修改成功')
    else:
        print('用户密码修改失败')
    return redirect(url_for('user.profile'))


@main.route('/update_avatar', methods=['POST'])
@login_required
def update_avatar():
    u = current_user()
    avatar = request.form.get('avatar', '')
    print('password', avatar)
    if u.change_avatar(avatar):
        print('修改成功')
    else:
        print('用户头像修改失败')
    return redirect(url_for('user.profile'))


@main.route('/profile', methods=['GET'])
def profile():
    u = current_user()
    if u is not None:
        print('profile', u.id, u.username, u.password)
        return render_template('user_profile.html', user=u)
    else:
        return redirect(url_for('.login_view'))

templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/pure-min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bbs.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/basic.css') }}">
    {% block css %}{% endblock %}

    <script src="/static/js/jquery-3.0.0.min.js"></script>
    {% block script %}{% endblock %}
</head>
<body>
    <nav id="id-nav">
        <a class="gua-nav-link gua-active" href="/node">首页</a>
        <a class="gua-nav-link" href="{{ url_for('user.login_view') }}">注册</a>
        <a class="gua-nav-link" href="{{ url_for('user.login_view') }}">登录</a>
        <a class="gua-nav-link" href="{{ url_for('user.logout') }}">登出</a>
        <a class="gua-nav-link gua-right" href="{{ url_for('user.profile') }}">个人主页</a>
        <a class="gua-nav-image gua-right" href="/user/profile">
            <img class="gua-avatar" src="/static/img/default.jpg">
            <span style="display: none" id="id-span-current-user" data-id="147" data-is_admin="false" data-username="宇宙无敌奥特曼" data-qq="540380798" data-email="540380798@qq.com" data-avatar="/uploads/avatar/147.jpg"></span>
        </a>
    </nav>

    <div class="main">
        <div class="sidebar">
            <ul id="id-ul-board">
                <a href="/topic/new">发布新帖子</a>
                {% block sidebar %}
                {% endblock %}
            </ul>
        </div>
        {% block content %}
        {% endblock %}
    </div>

    <div class="bbs-bottom">
        <div class="bbs-bottom-content bbs-content-size">
            <div class="bbs-bottom-nav">
                <a href="#">关于</a>
                <span>&nbsp;·&nbsp;</span>
                <a href="#">FAQ</a>
                <span>&nbsp;·&nbsp;</span>
                <a href="#">鸣谢</a>
                <span>&nbsp;·&nbsp;</span>
                <a href="#">7人在线</a>
            </div>
            <div class="bbs-bottom-about">
                创意工作者们的社区<br>World is powered by solitude
            </div>
        </div>
    </div>
</body>
</html>

templates/node.html
{% extends "base.html" %}

{% block title %}
    {{ node.name }}
{% endblock %}

{% block content %}
    <div class="pure-g gua-main">
        <div class="pure-u-3-4 gua-center">
            <h1>{{ node.name }}</h1>
            <p>{{ node.description }}</p>
            <div id="id-question-container" class="gua-auto-list">
                {% for topic in node.topics %}
                <div id="id-topic-{{ topic.id }}" class="gua-block gua-activity">
                    <img class="gua-avatar" src="{{ topic.user.avatar }}">
                    <div class="gua-title">
                        <a class="gua-topic-link" href="{{ url_for('topic.show', id=topic.id) }}">
                            <div class="gua-topic-title">
                                {{ topic.title }}
                            </div>
                        </a>
                        <div class="gua-topic-time gua-auto-form">
                            <a class="gua-topic-link" href="{{ url_for('topic.show', id=topic.id) }}"></a>
                            <a href="/user/profile">{{ topic.user.username }}</a>
                            更新于： {{ topic.created_time }}
                            <!-- 这里应该只有管理员才能删除, 标记解决 -->
                        </div>

                        <div class="gua-topic-views">
                            {{ topic.comments_num }} / {{ topic.read_num }}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/node_index.html
{% extends "base.html" %}

{% block title %}
    nodes
{% endblock %}

{% block content %}
    <div>
        <form action="{{ url_for('.add') }}" method="post">
            <input type="text" name="name" placeholder="输入 name">
            <input type="text" name="description" placeholder="输入 description">
            <button>Add</button>
        </form>
    </div>

    {% for node in node_list %}
    <div>
        {{ node.id }} : <a href="{{ url_for('node.show', id=node.id) }}">{{ node.name }}</a>
    </div>
    {% endfor %}
{% endblock %}


{% block sidebar %}
    <h1>hello </h1>
    <a href="/node/new">创建新节点</a>
{% endblock %}

templates/node_new.html
{% extends "base.html" %}

{% block title %}
    创建新节点
{% endblock %}

{% block content %}
    <div>
        <form action="{{ url_for('.add') }}" method="post">
            <input type="text" name="name" placeholder="输入 name">
            <input type="text" name="description" placeholder="输入 description">
            <button>Add</button>
        </form>
    </div>
{% endblock %}


{% block sidebar %}
    <h1>hello </h1>
    <a href="/node/new">创建新节点</a>
{% endblock %}

templates/topic.html
{% extends "base.html" %}

{% block title %}
    {{ topic.title }}
{% endblock %}

{% block content %}
    <div class="pure-g gua-main">
        <div class="pure-u-3-4 gua-center">
            <!-- 问题 -->
            <div class="gua-block gua-activity">
                <img class="gua-avatar" src="{{ topic.user.avatar }}">
                <div class="gua-title">
                    {{ topic.title }}
                </div>
                <div>
                    <a href="/user/profile/756">{{ topic.user.username }}</a>
                    更新于： {{ topic.created_time }}
                </div>
                <div id="id-wrap-question">
                    <div class="gua-problem-cell">
                        <h3>帖子描述</h3>
                        <div class="markdown-body gua-auto-cell" data-key="expectation">
                            <p>{{ topic.content}}</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- 所有回答 -->
            {% for c in topic.comments %}
            <div id="id-block-answer">
                <div class="gua-block gua-answer gua-activity" data-id="5454">
                    <img class="gua-avatar" src="{{ c.user.avatar }}">
                    <div>
                        <a href="/user/profile/">{{ c.user.username }}</a>
                        回复于： {{ c.created_time }}
                    </div>
                    <div class="markdown-body" data-answer_id="5454">
                        <p>{{ c.content }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
            <!-- 添加回答 -->
            <div class="gua-block">
                <div id="id-form-answer-new">
                    <form action="{{ url_for('comment.add') }}" method="post">
                        <textarea class="gua-full gua-input gua-content" placeholder="输入回复内容" name="content"></textarea>
                        <input type="hidden" name="topic_id" value="{{ topic.id }}">
                        <button id="id-button-submit" class="pure-button pure-button-primary gua-full">发表回复</button>
                    </form>
                    <br><br><br><br>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/topic_index.html
{% extends "base.html" %}

{% block title %}
    topics 所有帖子
{% endblock %}

{% block content %}
    <div class="pure-g gua-main">
        <div class="pure-u-3-4 gua-center">
            <h1>所有帖子</h1>
            <div id="id-question-container" class="gua-auto-list">
                {% for topic in topic_list %}
                <div id="id-topic-{{ topic.id }}" class="gua-block gua-activity">
                    <img class="gua-avatar" src="{{ topic.user.avatar }}">
                    <div class="gua-title">
                        <a class="gua-topic-link" href="{{ url_for('topic.show', id=topic.id) }}">
                            <div class="gua-topic-title">
                                {{ topic.title }}
                            </div>
                        </a>
                        <div class="gua-topic-time gua-auto-form">
                            <a class="gua-topic-link" href="{{ url_for('topic.show', id=topic.id) }}"></a>
                            <a href="/user/profile">{{ topic.user.username }}</a>
                            更新于： {{ topic.created_time }}
                            <!-- 这里应该只有管理员才能删除, 标记解决 -->
                        </div>

                        <div class="gua-topic-views">
                            {{ topic.comments_num }} / {{ topic.read_num }}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block sidebar %}
    <h1>hello </h1>
{% endblock %}

templates/topic_new.html
{% extends "base.html" %}

{% block title %}
    发帖
{% endblock %}

{% block content %}
    <form action="{{ url_for('.add') }}" method="post">
        <input type="text" name="node_id" placeholder="输入 node id">
        <br>
        <input type="text" name="title" placeholder="输入 title">
        <br>
        <textarea type="text" name="content" placeholder="输入 content"></textarea>
        <br>
        <button>Add</button>
    </form>
{% endblock %}


{% block sidebar %}
    <h1>hello </h1>
    <a href="/node/new">发布新帖子</a>
{% endblock %}

templates/user_login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>login</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
        <script src="http://code.jquery.com/jquery-1.4.1.min.js"></script>
        <script src="{{ url_for('static', filename='js/login.js') }}"></script>
    </head>
    <body>
        <div class="lg-container">
            <div class="lg-main">
                <div class="lg-header">
                    <h1 class="title">登录</h1>
                    <h2>暂时开放注册</h2>
                </div>
                <div class="lg-form">
                    <div class="lg-tab">
                        <button id="id-tab-signup" type="button">注册</button>
                        <button id="id-tab-login" class="blue" type="button">登录</button>
                    </div>
                    <div id="id-div-login">
                        <form action="{{ url_for('.login') }}" method="post">
                            <div class="lg-form-textinput">
                                <div class="lg-input-wrapper">
                                    <input id="id-input-login-username" type="text" name="username" placeholder="用户名">
                                </div>
                                <div class="lg-input-wrapper">
                                    <input id="id-input-login-password" type="password" name="password" placeholder="密码">
                                </div>
                            </div>
                            <button id="id-button-login" class="button-big" type="submit">进入</button>
                        </form>
                    </div>
                    <div id="id-div-signup" class="none">
                        <form action="{{ url_for('.register') }}" method="post">
                            <div class="lg-form-textinput">
                                <div class="lg-input-wrapper">
                                    <input id="id-input-signup-username" type="text" name="username" placeholder="用户名(必须字母开头且不少于六位)">
                                </div>
                                <div class="lg-input-wrapper">
                                    <input id="id-input-signup-password" type="text" name="password" placeholder="密码(必须数字和字母组合且不少于六位)">
                                </div>
                            </div>
                            <button id="id-button-signup" class="button-big" type="submit">注册</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

templates/user_profile.html
{% extends "base.html" %}

{% block title %}
    {{ user.username }} 的个人资料
{% endblock %}

{% block content %}
<div class="pure-g gua-main">
    <div class="pure-u-3-4 gua-center">
        <div class="gua-block">
            <img class="gua-avatar" src="{{ user.avatar }}">
            <div>
                <!-- <div>
                    <form class="pure-form" action="/avatar/add" method="post" enctype="multipart/form-data">
                        选择头像：
                        <input name="file" accept="image/*" type="file">
                        <input value="上传" type="submit">
                    </form>
                </div> -->
                <div>
                  <form action="/user/update_avatar" method="post">
                    头像地址：
                    <input name="avatar" value="{{ user.avatar }}" style="width:400px;">
                    <button>修改头像</button>
                  </form>
                </div>
                <div>
                    <form method="post" action="/user/update_username">
                        <label for="username">用户名：</label>
                        <input value="{{ user.username }}" name="username" id="id-input-username">
                        <button id="id-button-modsignature">更新用户名</button>
                    </form>
                </div>
                <div>
                    <form action="/user/update_password" method="post">
                        <label for="password">重置密码：</label>
                        <input value="{{ user.password }}" name="password" placeholder="新密码" type="password">
                        <button type="submit">确定修改密码</button>
                    </form>
                </div>
            </div>
            <!-- <div>
                <a href="/questions/user/147">发帖列表 ： 2</a>
            </div>
            <div>回帖： 11</div> -->
        </div>
     </div>
</div>
{% endblock %}